image: docker:19

stages:
- releases

include:
  - project: 'org/it/ci-templates'
    file:
      - '/templates/.kaniko-release.yml'

release:
  stage: releases
  extends: [.kaniko-release]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      variables:
        KANIKO_TAG: dev
    - when: manual
      variables:
        KANIKO_TAG: dev

