image: docker:19

stages:
- releases

include:
  - project: 'org/it/ci-templates'
    file:
      - '/templates/.kaniko-release.yml'

release:
  stage: releases
  extends: [.kaniko-release]
  variables:
    KANIKO_IMAGE: pti-clima/pyseasonal
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      variables:
        KANIKO_TAG: dev
    - if: '$CI_COMMIT_BRANCH == "prod"'
      variables:
        KANIKO_TAG: prod
    - when: manual
