#!/usr/bin/env python
''' This is the configuration file defining a number of variables used in <pred2tercile_operational.py> '''

#configuration for cmcc35
variable_std_cmcc35 = ['pvpot','SPEI-3-M','fwi','msl','t2m','tp','si10','ssrd'] # standard model variable names used by the pySeasonal package. Here used to load the quantile threshold files and to write the output netCDF files generated by this script
variable_fc_cmcc35 = ['pvpot','SPEI-3-M','fwi','psl','tas','pr','sfcWind','rsds'] # variable name used in the file name, i.e. outside the file, ask collegues for data format harmonization
variable_fc_nc_cmcc35 = ['pvpot','SPEI-3-M','FWI','psl','tas','pr','sfcWind','rsds'] # variable name within the model netcdf file, may vary depending on source
time_name_cmcc35 = ['time','time','time','forecast_time','forecast_time','forecast_time','forecast_time','forecast_time'] #name of the time dimension within the model netcdf file, may vary depending on source
lon_name_cmcc35 = ['lon','lon','lon','x','x','x','x','x']
lat_name_cmcc35 = ['lat','lat','lat','y','y','y','y','y']
file_start_cmcc35 = ['seasonal-original-single-levels','seasonal-original-single-levels_masked','seasonal-original-single-levels','seasonal-original-single-levels','seasonal-original-single-levels','seasonal-original-single-levels','seasonal-original-single-levels','seasonal-original-single-levels'] #start string of the file names

#configuration for eccc5
variable_std_eccc5 = ['pvpot','fwi','msl','t2m','tp','si10','ssrd'] # standard model variable names used by the pySeasonal package. Here used to load the quantile threshold files and to write the output netCDF files generated by this script
variable_fc_eccc5 = ['pvpot','fwi','psl','tas','pr','sfcWind','rsds'] # variable name used in the file name, i.e. outside the file, ask collegues for data format harmonization
variable_fc_nc_eccc5 = ['pvpot','FWI','psl','tas','pr','sfcWind','rsds'] # variable name within the model netcdf file, may vary depending on source
time_name_eccc5 = ['time','time','forecast_time','forecast_time','forecast_time','forecast_time','forecast_time'] #name of the time dimension within the model netcdf file, may vary depending on source
lon_name_eccc5 = ['lon','lon','x','x','x','x','x']
lat_name_eccc5 = ['lat','lat','y','y','y','y','y']
file_start_eccc5 = ['seasonal-original-single-levels','seasonal-original-single-levels','seasonal-original-single-levels','seasonal-original-single-levels','seasonal-original-single-levels','seasonal-original-single-levels','seasonal-original-single-levels'] #start string of the file names

#configuration for ecmwf51
variable_std_ecmwf51 = ['pvpot','SPEI-3-M','fwi','msl','t2m','tp','si10','ssrd'] # standard model variable names used by the pySeasonal package. Here used to load the quantile threshold files and to write the output netCDF files generated by this script
variable_fc_ecmwf51 = ['pvpot','SPEI-3-M','fwi','psl','tas','pr','sfcWind','rsds'] # variable name used in the file name, i.e. outside the file, ask collegues for data format harmonization
variable_fc_nc_ecmwf51 = ['pvpot','SPEI-3-M','FWI','psl','tas','pr','sfcWind','rsds'] # variable name within the model netcdf file, may vary depending on source
time_name_ecmwf51 = ['time','time','time','forecast_time','forecast_time','forecast_time','forecast_time','forecast_time'] #name of the time dimension within the model netcdf file, may vary depending on source
lon_name_ecmwf51 = ['lon','lon','lon','x','x','x','x','x']
lat_name_ecmwf51 = ['lat','lat','lat','y','y','y','y','y']
file_start_ecmwf51 = ['seasonal-original-single-levels','seasonal-original-single-levels_masked','seasonal-original-single-levels','seasonal-original-single-levels','seasonal-original-single-levels','seasonal-original-single-levels','seasonal-original-single-levels','seasonal-original-single-levels'] #start string of the file names
