---

obs: 'PTI-grid-v4' #name of the observational / reanalysis dataset that will be regridded: 'era5', 'PTI-grid-v2', 'PTI-grid-v4'
agg_src: 'mon' #'day' or 'mon': temporal aggregation of the observational input files, pertains to the <obs> loop indicated with <oo> below

# variables: ['TXm', 'CGDDS_up010', 'FWI_up010', 'SPEI-3_up010', 'SU_up010', 'TR_up010', 'Rx1day_up010', 'Rx5day_up010', 'PRtot_up010', 'PRm_up010', 'TNm_up010', 'TXm_up010', 'FD_up010'] #variables to be regridded
# variables_nc: ['TXm', 'CGDDS', 'FWI', 'SPEI-3', 'SU', 'TR', 'Rx1day', 'Rx5day', 'PRtot', 'PRm', 'TNm', 'TXm', 'FD'] #variable names with the netCDF file
# variables: ['TXm', 'FWI', 'SU', 'TR', 'Rx1day', 'Rx5day', 'PRm', 'TNm', 'FD', 'CDDX', 'DD', 'ID'] #variables to be regridded
# variables_nc: ['TXm', 'FWI', 'SU', 'TR', 'Rx1day', 'Rx5day', 'PRm', 'TNm', 'FD', 'CDDX', 'DD', 'ID'] #variable names with the netCDF file

variables: ['SPEI-3', 'Tm', 'TXm', 'TNm', 'SU', 'TR', 'ID', 'FD', 'WSm', 'PRm', 'DD', 'Rx1day', 'UAI', 'pet-hargreaves', 'FWIm'] #list containing the variables to be regridded
variables_nc: ['SPEI-3', 'Tm', 'TXm', 'TNm', 'SU', 'TR', 'ID', 'FD', 'WSm', 'PRm', 'DD', 'Rx1day', 'UAI', 'pet-hargreaves', 'FWIm'] #list containing the variable names with the netCDF file
variables_out: ['SPEI-3', 'Tm', 'TXm', 'TNm', 'SU', 'TR', 'ID', 'FD', 'WSm', 'PRm', 'DD', 'Rx1day', 'UAI', 'pet-hargreaves', 'FWIm'] #list containing the variable names with the netCDF file

startyears_file: [1981, 1981, 1981, 1981, 1981, 1981, 1981, 1981, 1981, 1981, 1981, 1981, 1981, 1981, 1981] #list containing the start year of the obs file as indicated in filename
endyears_file: [2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023] #list containing the corresponding end year as indicated in filename
startyears_aggregation: [1981, 1981, 1981, 1981, 1981, 1981, 1981, 1981, 1981, 1981, 1981, 1981, 1981, 1981, 1981] #deprecated because no longer used in aggregate_obs.py; list containing the start years to be aggregated
endyears_aggregation: [2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023] #deprecated because no longer used in aggregate_obs.py; list containing the end years to be aggregated

domain: 'Iberia' #spatial domain the model data is available on. So far, this is just a label used in the output filename
domain_label: 'pen' #domain label used in file name
resolution: '10km' #resolution shortcut used in the input variable names

grid_name: 'PTI-grid-v4' #here used as label to save the output netcdf file: ecmwf51 for 1 degree datasets, PTI-grid-v2 for downscaled datasets

paths:
  home: '/lustre/gmeteo/PTICLIMA'
  path_obs_base: 'DATA/OBSERVATIONS' #base path upon which the final path to the obs data is constructed
  savepath_base: 'Results/seasonal/obs/regridded' #This is the common directory for regridded monthly observations; what is placed here will be processed by get_skill_season.py
  rundir: 'Scripts/SBrands/pyPTIclima/pySeasonal' #The run directory