#!/usr/bin/env python

## set the variables for which the values over the sea will be removed, the suffix <std> refers to the effect that the standard variable names used by the pySeasonal package have to be used here
mask_dir = '/lustre/gmeteo/PTICLIMA/Auxiliary-material/Masks' #path to the land-sea masks on lustre
masked_variable_std = ['fwi','SPEI-3-M'] #list of variables on which a land-sea mask will be applied, setting values over sea to nan

## set the lead-times for each model and version version thereof, as well as for each aggregation window (currently 1 and 3 months) 

# ECMWF SEAS5.1
nr_mem_ecmwf51 = 25 #number of members to be considered in the verification
years_ecmwf51 = [1981,2023] # list containing the start and end years of the verification period for this model; refers to the first and the last year of the monthly model inits; may contain the combined hindcasts and forecasts; years must coincide with the years indicated in the name of model netCDF file generated by aggregate_hindcast.py
lead_ecmwf51_1mon = [[0],[1],[2],[3],[4],[5],[6]] #lead-months per season for an aggregation window of 1 month
lead_ecmwf51_2mon = [[0,1],[1,2],[2,3],[3,4],[4,5],[5,6]] #lead-months per season for an aggregation window of 3 months
lead_ecmwf51_3mon = [[0,1,2],[1,2,3],[2,3,4],[3,4,5],[4,5,6]] #lead-months per season for an aggregation window of 3 months
lead_ecmwf51_4mon = [[0,1,2,3],[1,2,3,4],[2,3,4,5],[3,4,5,6]] #lead-months per season for an aggregation window of 4 months
lead_ecmwf51_5mon = [[0,1,2,3,4],[1,2,3,4,5],[2,3,4,5,6]] #lead-months per season for an aggregation window of 5 months

# CMCC-SPS3.5 (System 35 in CDS)
nr_mem_cmcc35 = 40
years_cmcc35 = [1993,2023]
lead_cmcc35_1mon = [[0],[1],[2],[3],[4],[5]]
lead_cmcc35_2mon = [[0,1],[1,2],[2,3],[3,4],[4,5]] #lead-months per season for an aggregation window of 3 months
lead_cmcc35_3mon = [[0,1,2],[1,2,3],[2,3,4],[3,4,5]]
lead_cmcc35_4mon = [[0,1,2,3],[1,2,3,4],[2,3,4,5]] #lead-months per season for an aggregation window of 4 months
lead_cmcc35_5mon = [[0,1,2,3,4],[1,2,3,4,5]] #lead-months per season for an aggregation window of 5 months

# CMCC-SPS4 (System 4 in CDS)
nr_mem_cmcc4 = 30
years_cmcc4 = [1993,2023]
lead_cmcc4_1mon = [[0],[1],[2],[3],[4],[5]]
lead_cmcc4_2mon = [[0,1],[1,2],[2,3],[3,4],[4,5]] #lead-months per season for an aggregation window of 3 months
lead_cmcc4_3mon = [[0,1,2],[1,2,3],[2,3,4],[3,4,5]]
lead_cmcc4_4mon = [[0,1,2,3],[1,2,3,4],[2,3,4,5]] #lead-months per season for an aggregation window of 4 months
lead_cmcc4_5mon = [[0,1,2,3,4],[1,2,3,4,5]] #lead-months per season for an aggregation window of 5 months

# ECCC System 5, based on the CanESM5.1p1bc atmosphere and terrestial ecosystem coupled model; see https://confluence.ecmwf.int/display/CKB/Description+of+CanESM5.1p1bc-v20240611+C3S+contribution
nr_mem_eccc5 = 20
years_eccc5 = [1993,2023]
lead_eccc5_1mon = [[0],[1],[2],[3],[4],[5],[6]]
lead_eccc5_2mon = [[0,1],[1,2],[2,3],[3,4],[4,5],[5,6]] #lead-months per season for an aggregation window of 3 months
lead_eccc5_3mon = [[0,1,2],[1,2,3],[2,3,4],[3,4,5],[4,5,6]]
lead_eccc5_4mon = [[0,1,2,3],[1,2,3,4],[2,3,4,5],[3,4,5,6]] #lead-months per season for an aggregation window of 4 months
lead_eccc5_5mon = [[0,1,2,3,4],[1,2,3,4,5],[2,3,4,5,6]] #lead-months per season for an aggregation window of 5 months

# set season labels for a 1 and 3 months aggregation period
season_label_1mon = ['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC']
season_label_2mon = ['DJ','JF','FM','MA','AM','MJ','JJ','JA','AS','SO','ON','ND']
season_label_3mon = ['DJF','JFM','FMA','MAM','AMJ','MJJ','JJA','JAS','ASO','SON','OND','NDJ']
season_label_4mon = ['DJFM','JFMA','FMAM','MAMJ','AMJJ','MJJA','JJAS','JASO','ASON','SOND','ONDJ','NDJF']
season_label_5mon = ['DJFMA','JFMAM','FMAMJ','MAMJJ','AMJJA','MJJAS','JJASO','JASON','ASOND','SONDJ','ONDJF','NDJFM']

# set month definitions for a 1 and 3 months aggregation period
season_1mon = [[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12]] # 1 month
season_2mon = [[12,1],[1,2],[2,3],[3,4],[4,5],[5,6],[6,7],[7,8],[8,9],[9,10],[10,11],[11,12]] # 2 months
season_3mon = [[12,1,2],[1,2,3],[2,3,4],[3,4,5],[4,5,6],[5,6,7],[6,7,8],[7,8,9],[8,9,10],[9,10,11],[10,11,12],[11,12,1]] # 3 months
season_4mon = [[12,1,2,3],[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7],[5,6,7,8],[6,7,8,9],[7,8,9,10],[8,9,10,11],[9,10,11,12],[10,11,12,1],[11,12,1,2]] # 4 months
season_5mon = [[12,1,2,3,4],[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8],[5,6,7,8,9],[6,7,8,9,10],[7,8,9,10,11],[8,9,10,11,12],[9,10,11,12,1],[10,11,12,1,2],[11,12,1,2,3]] # 5 months