---

# Configuration file for seas2ipe.py script

# Version and model configuration
version: 'v1r'  # version number of the validation results
model: ['ecmwf']  # list containing the acronyms of the models to be assessed
model_version: ['51']  # list containing the versions of these models
obs: 'PTI-grid-v2'  # string containing the observational reference

# Quantile and validation configuration
years_quantile: [[1993, 2022]]  # list containing the years used to calculate quantiles, one sub-list per model
subperiod: 'none'  # climate oscillation: "enso" or "none"
scores: ['roc_auc_lower_tercile_skillscore_binary','roc_auc_center_tercile_skillscore_binary','roc_auc_upper_tercile_skillscore_binary']  # list containing the binary skill masks for the ROC AUC Skill Score fore each tercile
agg_labels: ['3mon']  # considered aggregation windows
nan_placeholder: 0

# Variable mapping to PTI format
# variables_std: ['GDD_S-i1', 'GDD_W-i1', 'fwi-i1', 'pvpot-i1', 'SPEI-3-M-i1', 'tp-i1', 'ssrd-i1', 'si10-i1', 't2m-i1']  # standardized variable names
# variables_out: ['cgdd_s', 'cgdd_w', 'fwi', 'pvpot', 'spei3', 'rti', 'ssrd', 'fg', 'gtg']  # output variable names, as defined in PTI-Clima variable table: https://docs.google.com/spreadsheets/d/1K5n3aM0vGgnJEwlghjK1BtqJr0Ug0mQYlzZKQxB2wJU/edit?gid=0#gid=0
variables_std: ['fwi-i1', 'pvpot-i1', 'SPEI-3-M-i1', 'tp-i1', 'ssrd-i1', 'si10-i1', 't2m-i1']  # standardized variable names
variables_out: ['fwi', 'pvpot', 'spei3', 'rti', 'ssrd', 'fg', 'gtg']  # output variable names, as defined in PTI-Clima variable table: https://docs.google.com/spreadsheets/d/1K5n3aM0vGgnJEwlghjK1BtqJr0Ug0mQYlzZKQxB2wJU/edit?gid=0#gid=0
masked_variables_std: ['none']  # list of variables on which land-sea mask will be applied

# Data type and domain configuration
datatype: 'float32'  # data type of variables in output netcdf files
domain: 'Iberia'  # spatial domain
detrended: 'no'  # yes or no, linear detrending

# Path configuration
# These paths will be set based on GCM_STORE environment variable
paths:
  home: '/lustre/gmeteo/'
  server: 'WORK/WWW/PTICLIMA/PRODUCTS'
  path_gcm_base: 'PTICLIMA/DATA/SEASONAL/seasonal-original-single-levels'
  path_gcm_base_derived: 'PTICLIMA/DATA/SEASONAL/seasonal-original-single-levels_derived'
  path_gcm_base_masked: 'PTICLIMA/DATA/SEASONAL/seasonal-original-single-levels_masked'
  rundir: 'PTICLIMA/Scripts/SBrands/pyPTIclima/pySeasonal'
  dir_validation: 'PTICLIMA/Results/seasonal/validation'
  dir_forecast: 'PTICLIMA/Results/seasonal/forecast'
  dir_output: 'WORK/WWW/PTICLIMA/PRODUCTS/seas2ipe'
  mask_dir: 'PTICLIMA/Auxiliary-material/Masks'

# Quantile thresholds
quantile_threshold: [0.33, 0.67]

