#!/usr/bin/env python

'''interpolates tercile probabilities on medcof domain previously generated by get_skill_season.py to the higher resolution grids of the PTI Clima (Iberia and Canarias),
verifies them with the ROC AUC and generates a binary skill mask in the same format than those prodced by plot_seasonal_validation_results.py'''

#load packages
import sys
import numpy as np
import xarray as xr
import xskillscore as xs
import os
import pandas as pd
import time
import pdb #then type <pdb.set_trace()> at a given line in the code below
import psutil
import xskillscore as xs

from pyseasonal.utils.config import load_config
from pyseasonal.utils.functions_seasonal import apply_sea_mask, lin_detrend, get_reliability_or_roc

start_time = time.time()

if len(sys.argv) > 1:
    target_domain = str(sys.argv[1]) #a single character string pointing to the domain to which the medcof data are to be interpolated and on which the verification will take place
else:
    target_domain = 'Iberia'

if target_domain not in ('Iberia','Canarias'):
    raise ValueError('Check entry for <domain> !')

FLAGDIR = '/lustre/gmeteo/PTICLIMA/Scripts/SBrands/pyPTIclima/pySeasonal/FLAG/medcof2hr/'+target_domain

# CONSTRUCT CONFIGURATION FILE ###############################################

configuration_file = 'config/config_for_medcof2hr.yaml'

##############################################################################

# Load configuration
config = load_config(configuration_file)

# Extract paths from configuration
paths = config['paths'] # get paths from configuration
dir_netcdf = paths['dir_netcdf']
dir_telcon = paths['dir_telcon'] #directory of the netCDF file containing the phases of known teleconnection indices; currently ENSO only, as generated with oni2enso.py
mask_dir = paths['mask_dir'] # path to the land-sea masks on lustre

# Extract fixed input parameters from configuration
in_params = config['input_parameters']
vers = in_params['vers']
models = in_params['models']
obs = in_params['obs']
variable_out_label = in_params['variable_out_label']
domain = in_params['domain']
precision = in_params['precision']
compression_level = in_params['compression_level']
bin_edges_reliability = in_params['bin_edges_reliability']
agg_labels = in_params['agg_labels']
detrending = in_params['detrending']
masked_variables_std = in_params['masked_variables_std'] #is currently only applied to mask the modelled tercile probability time-series and the corresponding observed binary occurrence-absence (1/0) values
filename_telcon = in_params['filename_telcon'] #name of the file located in <dir_telcon>
modulators = in_params['modulators']
phases = in_params['phases']
modulator_ref = in_params['modulator_ref']
min_nr_events = in_params['min_nr_events']
interp_method = in_params['interp_method']
nr_prob_thesholds = in_params['nr_prob_thresholds']

prob_thresholds = np.linspace(0, 1, nr_prob_thesholds) #threshold probability values used to calculated ROC AUC

## EXECUTE #############################################################

#construct <subperiod> dimension used to save validation results
subperiods = []
for sp in np.arange(len(modulators)):
    if modulators[sp] == 'enso':
        subperiod_step = modulators[sp]+phases[sp]+modulator_ref
    elif modulators[sp] == 'none':
        subperiod_step = 'none'
    else:
        raise ValueError('Unexpected entry for modulators[sp] !')
    subperiods.append(subperiod_step)

#load the model-specific configuration previously set in the config/config_for_get_skill_season.py file
years_mod = [] #init list containing the start and end years of period to be evaluated for each model (may contain the combined hindcasts and forecasts); this list contains as many sub-lists as there are models to be validated
years_obs = []
variables_mod = []
variables_obs = []
lead = [] #init list containing the lead-time configuration for each model and aggregation window
for mm in np.arange(len(models)):
    years_mod_step = config['model_settings'][models[mm]]['years_mod']
    years_obs_step = config['model_settings'][models[mm]]['years_obs']
    variables_obs_step = config['model_settings'][models[mm]]['variables_obs'] #standardized variables names created by aggregate_obs.py
    variables_mod_step = config['model_settings'][models[mm]]['variables_mod'] #standardized variables names created by aggregate_hindcast.py
    years_mod.append(years_mod_step)
    years_obs.append(years_obs_step)
    variables_mod.append(variables_mod_step)
    variables_obs.append(variables_obs_step)

    leads_per_model = [] #init lead-times per model
    for ag in np.arange(len(agg_labels)):
        lead_step = config['model_settings'][models[mm]]['lead_'+agg_labels[ag]]
        leads_per_model.append(lead_step)
    lead.append(leads_per_model)

#print the variables built from the configuration files
print('------------------------------------------------')
print('THE FOLLOWNG CONFIGURATION HAS BEEN LOADED AND WILL BE PROCESSED:')
print('vers: '+str(vers))
print('models: '+str(models))
print('obs: '+str(obs))
print('variable_out_label: '+str(variable_out_label))
print('target_domain: ' +str(target_domain))
print('interp_method: ' +str(interp_method))
print('models: '+str(models))
print('agg_labels: '+str(agg_labels))
print('modulators: '+str(modulators))
print('phases: '+str(phases))
print('modulator_ref: '+str(modulator_ref))
print('min_nr_events: '+str(min_nr_events))
print('years_mod: '+str(years_mod))
print('years_obs: '+str(years_obs))
print('variables_mod: '+str(variables_mod))
print('variables_obs: '+str(variables_obs))
print('nr_prob_thresholds: '+str(nr_prob_thesholds))
print('------------------------------------------------')

dir_netcdf = dir_netcdf+'/'+vers #dir_netcdf is extended with the version directory

#create output directories needed by this script, if needed.
if os.path.isdir(dir_netcdf) != True:
    os.makedirs(dir_netcdf)
if os.path.isdir(FLAGDIR) != True:
    os.makedirs(FLAGDIR)

#read the file containing the different phases of known climate oscillation such as ENSO, this file has to be previously generated with oni2enso.py
indices = xr.open_dataset(dir_telcon+'/'+filename_telcon).astype(precision)

#get path to mask file as a function of the requested domain
if target_domain == 'Iberia':
    mask_file_indir = 'PTI-grid_Iberia_010_descending_lat_reformatted.nc'
elif target_domain == 'Canarias':
    # mask_file_indir = 'PTI-grid_Canarias_descending_lat_reformatted.nc' # 0.05 degree resolution
    mask_file_indir = 'PTI-grid_Canarias_0025_descending_lat_reformatted.nc' # 0.025 degree resolution
else:
    raise ValueError('Check entry for <domain> input parameter !')
mask_file = mask_dir+'/'+mask_file_indir #here, descending lats are needed (check why the DataArrays behave distinct concerning ascending or descending lats in pySeasonal)
nc_hr = xr.open_dataset(mask_file).rename({'lat':'y', 'lon':'x'})

for ag in np.arange(len(agg_labels)):
    #create output final output directory if it does not exist.
    dir_netcdf_tercilprobs_src = dir_netcdf+'/tercile_probabilities/'+domain+'/'+agg_labels[ag] #directory of input tercile probability files previously generated with get_skill_season.py
    dir_netcdf_tercilprobs_out = dir_netcdf+'/tercile_probabilities/'+target_domain+'/'+agg_labels[ag] #directory of output tercile probability files generated with this script
    dir_netcdf_skillmasks = dir_netcdf+'/skill_masks/'+target_domain+'/'+agg_labels[ag] #directory of the output skill masks generated by this script

    if os.path.isdir(dir_netcdf_tercilprobs_out) != True:
        os.makedirs(dir_netcdf_tercilprobs_out)
    if os.path.isdir(dir_netcdf_skillmasks) != True:
        os.makedirs(dir_netcdf_skillmasks)

    for mm in np.arange(len(models)):
        #create a numpy array containing all lead-months for models[mm]
        lead_arr = np.arange(np.array(lead[mm][ag]).min(),np.array(lead[mm][ag]).max()+1)
        #get label describing the considered lead-time
        lead_label = [str(lead[mm][ag][ll]).replace(',','').replace('[','').replace(']','').replace(' ','') for ll in np.arange(len(lead[mm][ag]))]

        for vv in np.arange(len(variables_mod[mm])):
            path_mod = dir_netcdf_tercilprobs_src+'/tercile_prob_pticlima_'+agg_labels[ag]+'_'+models[mm]+'_'+variables_mod[mm][vv]+'_'+domain+'_'+str(years_mod[mm][0])+'_'+str(years_mod[mm][-1])+'_'+vers+'.nc'
            path_obs = dir_netcdf_tercilprobs_src+'/tercile_bin_pticlima_'+agg_labels[ag]+'_'+obs+'_'+variables_obs[mm][vv]+'_'+domain+'_'+str(years_obs[mm][0])+'_'+str(years_obs[mm][-1])+'_'+vers+'.nc'

            #load tercile probabilities on medcof domain
            # nc_mod = xr.open_dataset(path_mod) #the first two dimensions are singleton and squeezed
            # nc_obs = xr.open_dataset(path_obs) #the first two dimensions are singleton and squeezed
            nc_mod = xr.open_dataset(path_mod).squeeze().drop_vars(['model','aggregation']) #the first two dimensions are singleton and squeezed
            nc_obs = xr.open_dataset(path_obs).squeeze().drop_vars(['obs','aggregation']) #the first two dimensions are singleton and squeezed

            #check whether model data and observations have the same time instances
            if np.all(nc_mod.time == nc_obs.time):
                print('Model data and observations have the same time instances ! Proceed with interpolation and verification....')
            else:
                raise ValueError('Model data and observations do not have the same time instances ! Check <nc_mod> and <nc_obs> !')

            #and interpolate them to the high resolution grid defined in <target_domain>
            nc_mod_hr = nc_mod.interp(y=nc_hr.y, x=nc_hr.x, method=interp_method).astype(precision).clip(min=0, max=1)
            nc_obs_hr = nc_obs.interp(y=nc_hr.y, x=nc_hr.x, method=interp_method).astype(precision)
            
            # tranform continuous observed probabilities obtained from interpolation into binary values
            # nc_obs_hr = (nc_obs_hr >= 0.5).astype(precision)
            nc_obs_hr = (nc_obs_hr >= 0.5).astype(precision)

            #clean
            nc_mod.close(); nc_obs.close()
            del(nc_mod,nc_obs)
            
            #apply land-sea masks to the just interpolated high resolution files
            nc_obs_hr = apply_sea_mask(nc_obs_hr,mask_file,'y','x')
            nc_mod_hr = apply_sea_mask(nc_mod_hr,mask_file,'y','x')
            
            #add attributes the the high resolution files
            nc_mod_hr.attrs['variable'] = variables_mod[mm][vv]+'-'+variable_out_label
            nc_obs_hr.attrs['variable'] = variables_obs[mm][vv]+'-'+variable_out_label
            nc_mod_hr.attrs['domain'] = target_domain+' interpolated from '+domain
            nc_obs_hr.attrs['domain'] = target_domain+' interpolated from '+domain
            nc_mod_hr.attrs['interpolation_method'] = interp_method
            nc_obs_hr.attrs['interpolation_method'] = interp_method

            #save interpolated hr files to netcdf format
            # for the model
            savename_nc_mod_hr = dir_netcdf_tercilprobs_out+'/tercile_prob_pticlima_'+agg_labels[ag]+'_'+models[mm]+'_'+variables_mod[mm][vv]+'-'+variable_out_label+'_'+target_domain+'_'+str(years_mod[mm][0])+'_'+str(years_mod[mm][-1])+'_'+vers+'.nc'
            encoding = {'upper_tercile_probability': {'zlib': True, 'complevel': compression_level}, 'center_tercile_probability': {'zlib': True, 'complevel': compression_level}, 'lower_tercile_probability': {'zlib': True, 'complevel': compression_level}}
            nc_mod_hr.to_netcdf(savename_nc_mod_hr,encoding=encoding)
            # of the observations
            savename_nc_obs_hr = dir_netcdf_tercilprobs_out+'/tercile_bin_pticlima_'+agg_labels[ag]+'_'+obs+'_'+variables_obs[mm][vv]+'-'+variable_out_label+'_'+target_domain+'_'+str(years_obs[mm][0])+'_'+str(years_obs[mm][-1])+'_'+vers+'.nc'
            encoding = {'upper_tercile_binary': {'zlib': True, 'complevel': compression_level}, 'center_tercile_binary': {'zlib': True, 'complevel': compression_level}, 'lower_tercile_binary': {'zlib': True, 'complevel': compression_level}}
            nc_obs_hr.to_netcdf(savename_nc_obs_hr,encoding=encoding)
            
            #create empty numpy array to be filled with ROC-AUC skill score values (dims = subperiod, detrended, variable, season, lead, y, x)
            # roc_lower_np = np.zeros((len(modulators),len(detrending),len(variables_mod[mm]),len(nc_mod_hr.season),len(nc_mod_hr.lead),len(nc_hr.y),len(nc_hr.x)))
            roc_lower_np = np.zeros((len(modulators),len(detrending),len(nc_mod_hr.season),len(nc_mod_hr.lead),len(nc_hr.y),len(nc_hr.x)))
            roc_center_np = np.copy(roc_lower_np)
            roc_upper_np = np.copy(roc_lower_np)           

            for mo in np.arange(len(modulators)):
                #get conditional verficiation results per lead-time
                for ll in np.arange(len(lead_label)):
                    if modulators[mo] == 'enso':
                        #check where the modulation is valid and shift the indices time series in case it is valid at the time of model initialization. Then get the time period common to the teleconnection index and the modelled and observed time series
                        if modulator_ref == 'init':
                            # indices_sub = indices.shift(time=int(lead_label[ll])) #shift the values in indices towards the future by lead_label[ll] months
                            indices_sub = indices.shift(time=int(lead_label[ll][0])) #shift the values in indices towards the future by lead_label[ll] months
                            indices_sub = indices_sub.isel(time=np.isin(indices_sub.time,nc_obs_hr.time)) #get common time period with observations, which in turn was syncronized with model data above
                        elif modulator_ref == 'valid':
                            indices_sub = indices.isel(time=np.isin(indices.time,nc_obs_hr.time)) #get common time period with observations, which in turn was syncronized with model data above
                        else:
                            raise ValueError('Check entry for <modulator_ref> input parameter !')
                        # phase_ind = (indices_sub.oni2enso == phases[mo]).values
                        phase_ind = (indices_sub.oni2enso == int(phases[mo])).values
                        
                        #check whether the minumum number of events set in <min_nr_events> is reached
                        if sum(phase_ind==False) < min_nr_events:
                            raise ValueError('<phase_ind> must at least contain '+str(min_nr_events)+' True values !')
                        print('Start conditional verifcation for lead label '+str(lead_label[ll])+' and '+modulators[mo]+phases[mo]+', which occurred on the following time instances:')
                    elif modulators[mo] == 'none':
                        indices_sub = indices.isel(time=np.isin(indices.time,nc_obs_hr.time)) #is not used below any more if modulators[mo] = 'none'
                        phase_ind = np.array([True]*len(nc_obs_hr.time)) #set all indices to True
                        print('Start unconditional verifcation for lead label '+str(lead_label[ll])+', and '+modulators[mo]+phases[mo]+' considering the full time series:')
                    else:
                        raise ValueError('Unknown entry for <modulators[mo]> input parameter !')
                    #print time instances to be verified
                    print(nc_obs_hr.upper_tercile_binary.isel(time=phase_ind).time) 
                    
                    start_time_roc = time.time()

                    #ROC-AUC
                    roc_lower_np[mo,:,:,ll,:,:] = xs.roc(nc_obs_hr.lower_tercile_binary.isel(time=phase_ind).sel(lead=lead_label[ll]), nc_mod_hr.lower_tercile_probability.isel(time=phase_ind).sel(lead=lead_label[ll]), bin_edges=prob_thresholds, dim='time', drop_intermediate=False, return_results='area').values
                    roc_center_np[mo,:,:,ll,:,:] = xs.roc(nc_obs_hr.center_tercile_binary.isel(time=phase_ind).sel(lead=lead_label[ll]), nc_mod_hr.center_tercile_probability.isel(time=phase_ind).sel(lead=lead_label[ll]), bin_edges=prob_thresholds, dim='time', drop_intermediate=False, return_results='area').values
                    roc_upper_np[mo,:,:,ll,:,:] = xs.roc(nc_obs_hr.upper_tercile_binary.isel(time=phase_ind).sel(lead=lead_label[ll]), nc_mod_hr.upper_tercile_probability.isel(time=phase_ind).sel(lead=lead_label[ll]), bin_edges=prob_thresholds, dim='time', drop_intermediate=False, return_results='area').values

                    del(phase_ind)

                    end_time_roc = time.time()
                    elapsed_time_roc = (end_time_roc - start_time_roc)/60
                    print('The execution time for caclulating the ROC-AUC for the 3 terciles was: '+str(elapsed_time_roc)+' minutes')
        
            #add singleton dimensions to numpy arrays as requested by Dani García
            roc_lower_np = np.expand_dims(roc_lower_np, axis=0)
            roc_center_np = np.expand_dims(roc_center_np, axis=0)
            roc_upper_np = np.expand_dims(roc_upper_np, axis=0)
            
            #transform numpy arrays with singleton dimension to xarray Data Array
            roc_lower = xr.DataArray(roc_lower_np, coords=[[variables_mod[mm][vv]], subperiods, nc_mod_hr.detrended, nc_mod_hr.season, nc_mod_hr.lead, nc_mod_hr.y, nc_mod_hr.x], dims=['variable', 'subperiod','detrended','season','lead','y','x'], name='roc_auc_lower_tercile').astype(precision)
            roc_center = xr.DataArray(roc_center_np, coords=[[variables_mod[mm][vv]], subperiods, nc_mod_hr.detrended, nc_mod_hr.season, nc_mod_hr.lead, nc_mod_hr.y, nc_mod_hr.x], dims=['variable', 'subperiod','detrended','season','lead','y','x'], name='roc_auc_center_tercile').astype(precision)
            roc_upper = xr.DataArray(roc_upper_np, coords=[[variables_mod[mm][vv]], subperiods, nc_mod_hr.detrended, nc_mod_hr.season, nc_mod_hr.lead, nc_mod_hr.y, nc_mod_hr.x], dims=['variable', 'subperiod','detrended','season','lead','y','x'], name='roc_auc_upper_tercile').astype(precision)
            
            #merge the roc of the 3 tericles into a single file
            roc = xr.merge((roc_lower,roc_center,roc_upper)).astype(precision)

            #clean
            nc_mod_hr.close(), nc_obs_hr.close(), roc_lower.close(); roc_center.close(); roc_upper.close()
            del(nc_mod_hr, nc_obs_hr, roc_lower, roc_center, roc_upper)

            #transform into ROC-AUC skill score; see https://doi.org/10.1007/s00382-019-04640-4
            roc_ss = (roc - 0.5) / 0.5
            roc_ss = roc_ss.rename({'roc_auc_lower_tercile' : 'roc_auc_lower_tercile_skillscore_continuous', 'roc_auc_center_tercile' : 'roc_auc_center_tercile_skillscore_continuous', 'roc_auc_upper_tercile' : 'roc_auc_upper_tercile_skillscore_continuous'})
            #transform to binary mask based on ROC-AUC skill score
            roc_ss_bin = (roc_ss > 0).astype(int)
            roc_ss_bin = roc_ss_bin.rename({'roc_auc_lower_tercile_skillscore_continuous' : 'roc_auc_lower_tercile_skillscore_binary', 'roc_auc_center_tercile_skillscore_continuous' : 'roc_auc_center_tercile_skillscore_binary', 'roc_auc_upper_tercile_skillscore_continuous' : 'roc_auc_upper_tercile_skillscore_binary'})
            
            #merge continuous and binary skill scores. Then add the "variable" dimension requested by Dani García as well as the corresponding metadata
            ds_mask_plus_cont = xr.merge((roc_ss,roc_ss_bin)).astype(precision)

            #clean
            roc_ss.close(), roc_ss_bin.close()
            del(roc_ss, roc_ss_bin)

            #apply land-sea mask
            ds_mask_plus_cont = apply_sea_mask(ds_mask_plus_cont,mask_file,'y','x').astype(precision)
            
            # add global attributes
            ds_mask_plus_cont.attrs['version'] = vers
            ds_mask_plus_cont.attrs['domain'] = target_domain
            ds_mask_plus_cont.attrs['mother_domain'] = domain
            ds_mask_plus_cont.attrs['interpolation_method'] = interp_method
            ds_mask_plus_cont.attrs['variable_mod'] = variables_mod[mm][vv]
            ds_mask_plus_cont.attrs['variable_obs'] = variables_obs[mm][vv]
            ds_mask_plus_cont.attrs['variable'] = variables_obs[mm][vv]+'-'+variable_out_label
            ds_mask_plus_cont.attrs['model'] = models[mm]
            ds_mask_plus_cont.attrs['accumulation_period'] = agg_labels[ag]
            ds_mask_plus_cont.attrs['AUC_probability_thresholds'] = str(nr_prob_thesholds)
            ds_mask_plus_cont.attrs['nan_criterion'] = 'A nan is set at a given grid-box if it is returned by xskillscore, e.g. due to a division by zero. It has been confirmed that this occcurs, e.g., if it does not rain at all either in the modelled or quasi-observed time-series. Grid boxes over the sea are also set to nan.'
            ds_mask_plus_cont.attrs['nan_over_sea'] = 'yes'
            ds_mask_plus_cont.attrs['validation_period'] = str(years_mod[mm]).replace('[','').replace(']','').replace(', ',' to ')+', grouped by subperiods as indicated by the <subperiod> coordinate'
            ds_mask_plus_cont.attrs['author'] = "Swen Brands (Instituto de Fisica de Cantabria, CSIC-UC), email: brandssf@ifca.unican.es"
           

            # add dimension and variable attributes
            ds_mask_plus_cont['subperiod'].attrs['info'] = 'Verification subperiod: <none> for no subperiod, <enso0init> for neutral ENSO events, <enso1init> for warm / El Niño events and <enso2init> for cold / La Niña events. Condition is valid on the month the model is initialized and becomes available, which is indicated by the <init> suffix.'
            ds_mask_plus_cont['detrended'].attrs['info'] = 'Linear de-trending was applied to the modelled and (quasi)observed time series prior to validation; yes or no'
            # ds_mask_plus_cont['variable'].attrs['info'] = 'Meteorological variable acronym according to ERA5 nomenclature followed by Copernicus Climate Data Store (CDS)'
            ds_mask_plus_cont['season'].attrs['info'] = 'Season the forecast is valid for'
            ds_mask_plus_cont['lead'].attrs['info'] = 'Leadtime of the forecast; one per month'
            ds_mask_plus_cont['y'].attrs['name'] = 'latitude'
            ds_mask_plus_cont['y'].attrs['standard_name'] = 'latitude'
            ds_mask_plus_cont['x'].attrs['name'] = 'longitude'
            ds_mask_plus_cont['x'].attrs['standard_name'] = 'longitude'

            #save the binary mask xarray dataset and close
            savename_netcdf = dir_netcdf_skillmasks+'/skill_masks_pticlima_'+target_domain+'_'+agg_labels[ag]+'_'+models[mm]+'_'+variables_mod[mm][vv]+'-'+variable_out_label+'_'+vers+'.nc'
            #define and apply chunks
            chunks = {"subperiod": len(ds_mask_plus_cont.subperiod),"detrended": len(ds_mask_plus_cont.detrended), "season" : 1, "lead" : 1 ,"y": round(len(ds_mask_plus_cont.y)/2),"x": round(len(ds_mask_plus_cont.x)/2)}
            ds_mask_plus_cont.chunk(chunks)
            #compress with zlib and shuffle=True
            encoding = {var: {"zlib": True,"complevel": 5,"shuffle": True,"dtype": "float32"} for var in ds_mask_plus_cont.data_vars}
            ds_mask_plus_cont.to_netcdf(savename_netcdf, engine = 'netcdf4', encoding = encoding)

            #clean
            ds_mask_plus_cont.close()
            del(ds_mask_plus_cont)
            
print('INFO: medcof2hr.py has been run successfully. A flag is written at '+FLAGDIR)
flagfile = FLAGDIR+'/medcof2hr_'+str(vers)+'_'+target_domain+'_'+str(models)+'_'+str(variables_mod)+'_'+str(agg_labels)+'_'+str(modulators)+'_'+str(phases)+'.flag'
flagfile = flagfile.replace("[","").replace("]","").replace("'","").replace(",","_").replace(" ","")
file = open(flagfile,'w')
file.write('medcof2hr.py has been run successfully for '+str(vers)+', '+target_domain+', '+str(models)+', '+str(variables_obs)+', '+str(variables_mod)+', '+str(agg_labels)+', '+str(modulators)+', '+str(phases))
file.close()
#print the elapsed time and close
end_time = time.time()
elapsed_time = (end_time - start_time)/60
print('The execution time of the entire script was: '+str(elapsed_time)+' minutes')
quit()
